create extension if not exists vector with schema extensions;

create table if not exists public.kb_chunks (
  id bigint generated by default as identity primary key,
  kb_id text not null,
  chunk_index integer not null,
  section_number integer not null,
  section_title text not null,
  source text not null,
  content text not null,
  embedding extensions.vector(768) not null,
  unique (kb_id, chunk_index)
);

alter table public.kb_chunks enable row level security;

create or replace function public.match_kb_chunks(
  query_embedding extensions.vector(768),
  match_count integer default 4,
  match_threshold real default 0.35,
  kb_id_filter text default 'lumen-student-handbook-2026-2027'
)
returns table (
  id bigint,
  chunk_index integer,
  section_number integer,
  section_title text,
  source text,
  content text,
  similarity real
)
language sql
stable
as $$
  select
    chunks.id,
    chunks.chunk_index,
    chunks.section_number,
    chunks.section_title,
    chunks.source,
    chunks.content,
    (1 - (chunks.embedding <=> query_embedding))::real as similarity
  from public.kb_chunks as chunks
  where chunks.kb_id = kb_id_filter
    and 1 - (chunks.embedding <=> query_embedding) >= match_threshold
  order by chunks.embedding <=> query_embedding
  limit match_count;
$$;

grant execute on function public.match_kb_chunks(extensions.vector, integer, real, text) to service_role;
